# Generated by Django 2.0 on 2020-01-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_peso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='peso',
            field=models.FloatField(verbose_name='Peso'),
        ),
    ]
