# Generated by Django 2.0 on 2020-01-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_peso', '0003_auto_20200120_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estatura',
            field=models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Estatura'),
        ),
    ]
